### ISSUE TITLE
public-review-announce subsection needs rewording

### ISSUE THREAD

**Issue by r12a** [w3c/documentreview#2]
> General announcement 
>   Use public-review-announce@w3.org for general announcements regarding wide and horizontal reviews

The i18n Chair raised a concern about this paragraph, because we think it is subverting the normal review request process (based on recent experience). 

It suggests that groups just need to send an email to that list, and can ignore the preceding instructions. We should consider how to improve the wording.

This subsection is presumably the instruction for engaging the public for wide review, rather than the horizontal activities (?).   If so, we should make that clear, and make it clear that the WG should use the prescribed methods for engaging the HR groups, instead of relying on them to pick up on mail in that list.  (They should engage directly with the HR groups (and should run self-reviews beforehand, whenever possible).)

**Comment by r12a** [comment]
Perhaps one thing that would help would be to visually group the HR information as subbullets under a "Horizontal Review Groups" header, ie. this structure:

* HR Groups
  * Accessibility
  * Architecture
  * ...
* Groups listed in your charter
* General announcement

That would probably also look less daunting to the reader.

**Comment by r12a** [comment]
On a separate email @samuelweiler clarified that there is an autoresponder sent to people who send email to the public-review-announce list.  The content of that is:

> If you are seeking review from specific W3C horizontal review groups,
> please follow the steps at:
> 
>     https://www.w3.org/wiki/DocumentReview#How_to_get_horizontal_review
> 
> MERELY EMAILING THIS LIST IS NOT SUFFICIENT.
> 
> This list may draw some attention to your document and get some
> comments, but it usually will not start the process wheels turning for
> W3C's formal review groups - these groups prefer targeted requests,
> indicating that the time for review is most ripe.

That helps, but it is probably still a good idea to set the expectations clearly in this doc, too.

**Comment by xfq** [comment]
WICG still seems to recommend sending emails to public-review-announce@w3.org.

See https://github.com/WICG/admin/wiki/Process-to-transfer-a-repo

**Comment by r12a** [comment]
I don't think we're deprecating use of the public-review-announce list. We're just saying that if you want to request a horizontal review, it's not enough to just send an email there: you need to follow the steps outlined in the documentreview page.

i'm happy to be corrected, but sending an email there to tell people you have transferred a repo seems fine.

**Comment by samuelweiler** [comment]
It currently says "Use public-review-announce@w3.org for general announcements regarding wide and horizontal reviews. (Sending an email to this list alone is not sufficient to trigger horizontal reviews. You will still need to formally request review from the Horizontal Groups, as described above.)". It seems to me that the parenthetical is sufficient. @r12a, are you content with the current content?

@xfq, thanks for flagging the WICG doc.  I updated it.

**Comment by r12a** [comment]
> @r12a, are you content with the current content?

Yep, I think the paren stuff is good. It may be worth putting an em tag around next time someone is making changes.

So i'm closing this now.
