### ISSUE TITLE
Email-centric rather than GitHub tag-centric

### ISSUE THREAD

**Issue by svgeesus** [w3c/documentreview#9]
[The review guidelines](https://www.w3.org/Guide/documentreview) seem very email-centric.

In some cases this is correct or partially correct, for example security review is still by sending an email to [the list for the now-closed Security IG](mailto:public-web-security@w3.org) - although even there, putting the answers to the security review in a GH issue could be mentioned.

But is APA review, for example, really best triggered by an email, rather than using the GH labels as documented later in the section? The [A11y review tracker](https://www.w3.org/PM/horizontal/?repo=w3c/a11y-review) on the other hand seems to assume GH labels.

**Comment by r12a** [comment]
@samuelweiler @michael-n-cooper i think this is for you.

**Comment by svgeesus** [comment]
As recent examples, [email request for A11y review](https://lists.w3.org/Archives/Public/public-apa/2020Oct/0000.html) which they [turned into a GH issue](https://github.com/w3c/css-a11y/issues/42), and [email request for Privacy review](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0000.html) which they [turned into a GH issue](https://github.com/w3cping/privacy-reviews/issues/18)

**Comment by samuelweiler** [comment]
I think this was resolved by https://github.com/w3c/documentreview/pull/13 and related process changes in March 2021.  @svgeesus, may we close this?

**Comment by svgeesus** [comment]
Thanks, @samuelweiler
